// Copyright (c) 2019 RRZE, University Erlangen-Nuremberg
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// WARNING: This file has automatically been generated on Sun, 29 May 2022 03:45:36 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package rocm_smi

/*
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files
#cgo CFLAGS:
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include "rocm_smi/rocm_smi.h"
#include "rocm_smi/kfd_ioctl.h"
#include "rocm_smi/rocm_smi_helpers.h"
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// rsmi_init function as declared in rocm_smi/rocm_smi.h:982
func rsmi_init(Init_flags uint64) RSMI_status {
	cInit_flags, cInit_flagsAllocMap := (C.ulonglong)(Init_flags), cgoAllocsUnknown
	__ret := C.rsmi_init(cInit_flags)
	runtime.KeepAlive(cInit_flagsAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_shut_down function as declared in rocm_smi/rocm_smi.h:989
func rsmi_shut_down() RSMI_status {
	__ret := C.rsmi_shut_down()
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_num_monitor_devices function as declared in rocm_smi/rocm_smi.h:1010
func rsmi_num_monitor_devices(Num_devices *uint32) RSMI_status {
	cNum_devices, cNum_devicesAllocMap := (*C.uint32_t)(unsafe.Pointer(Num_devices)), cgoAllocsUnknown
	__ret := C.rsmi_num_monitor_devices(cNum_devices)
	runtime.KeepAlive(cNum_devicesAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_id_get function as declared in rocm_smi/rocm_smi.h:1039
func rsmi_dev_id_get(Dv_ind uint32, Id *uint16) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_id_get(cDv_ind, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_sku_get function as declared in rocm_smi/rocm_smi.h:1066
func rsmi_dev_sku_get(Dv_ind uint32, Sku *byte) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSku, cSkuAllocMap := (*C.char)(unsafe.Pointer(Sku)), cgoAllocsUnknown
	__ret := C.rsmi_dev_sku_get(cDv_ind, cSku)
	runtime.KeepAlive(cSkuAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_vendor_id_get function as declared in rocm_smi/rocm_smi.h:1091
func rsmi_dev_vendor_id_get(Dv_ind uint32, Id *uint16) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_vendor_id_get(cDv_ind, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_name_get function as declared in rocm_smi/rocm_smi.h:1127
func rsmi_dev_name_get(Dv_ind uint32, Name *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_name_get(cDv_ind, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_brand_get function as declared in rocm_smi/rocm_smi.h:1161
func rsmi_dev_brand_get(Dv_ind uint32, Brand *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBrand, cBrandAllocMap := (*C.char)(unsafe.Pointer(Brand)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_brand_get(cDv_ind, cBrand, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cBrandAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_vendor_name_get function as declared in rocm_smi/rocm_smi.h:1197
func rsmi_dev_vendor_name_get(Dv_ind uint32, Name *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vendor_name_get(cDv_ind, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_vram_vendor_get function as declared in rocm_smi/rocm_smi.h:1222
func rsmi_dev_vram_vendor_get(Dv_ind uint32, Brand *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBrand, cBrandAllocMap := (*C.char)(unsafe.Pointer(Brand)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vram_vendor_get(cDv_ind, cBrand, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cBrandAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_serial_number_get function as declared in rocm_smi/rocm_smi.h:1253
func rsmi_dev_serial_number_get(Dv_ind uint32, Serial_num *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSerial_num, cSerial_numAllocMap := (*C.char)(unsafe.Pointer(Serial_num)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_serial_number_get(cDv_ind, cSerial_num, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cSerial_numAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_subsystem_id_get function as declared in rocm_smi/rocm_smi.h:1278
func rsmi_dev_subsystem_id_get(Dv_ind uint32, Id *uint16) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_id_get(cDv_ind, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_subsystem_name_get function as declared in rocm_smi/rocm_smi.h:1315
func rsmi_dev_subsystem_name_get(Dv_ind uint32, Name *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cName, cNameAllocMap := (*C.char)(unsafe.Pointer(Name)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.size_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_name_get(cDv_ind, cName, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cNameAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_drm_render_minor_get function as declared in rocm_smi/rocm_smi.h:1335
func rsmi_dev_drm_render_minor_get(Dv_ind uint32, Minor *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cMinor, cMinorAllocMap := (*C.uint32_t)(unsafe.Pointer(Minor)), cgoAllocsUnknown
	__ret := C.rsmi_dev_drm_render_minor_get(cDv_ind, cMinor)
	runtime.KeepAlive(cMinorAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_subsystem_vendor_id_get function as declared in rocm_smi/rocm_smi.h:1359
func rsmi_dev_subsystem_vendor_id_get(Dv_ind uint32, Id *uint16) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.uint16_t)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_subsystem_vendor_id_get(cDv_ind, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_unique_id_get function as declared in rocm_smi/rocm_smi.h:1382
func rsmi_dev_unique_id_get(Dv_ind uint32, Id *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cId, cIdAllocMap := (*C.ulonglong)(unsafe.Pointer(Id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_unique_id_get(cDv_ind, cId)
	runtime.KeepAlive(cIdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_pci_bandwidth_get function as declared in rocm_smi/rocm_smi.h:1409
func rsmi_dev_pci_bandwidth_get(Dv_ind uint32, Bandwidth *RSMI_pcie_bandwidth) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBandwidth, cBandwidthAllocMap := (*C.rsmi_pcie_bandwidth_t)(unsafe.Pointer(Bandwidth)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_bandwidth_get(cDv_ind, cBandwidth)
	runtime.KeepAlive(cBandwidthAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_pci_id_get function as declared in rocm_smi/rocm_smi.h:1446
func rsmi_dev_pci_id_get(Dv_ind uint32, Bdfid *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBdfid, cBdfidAllocMap := (*C.ulonglong)(unsafe.Pointer(Bdfid)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_id_get(cDv_ind, cBdfid)
	runtime.KeepAlive(cBdfidAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_topo_numa_affinity_get function as declared in rocm_smi/rocm_smi.h:1470
func rsmi_topo_numa_affinity_get(Dv_ind uint32, Numa_node *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cNuma_node, cNuma_nodeAllocMap := (*C.uint32_t)(unsafe.Pointer(Numa_node)), cgoAllocsUnknown
	__ret := C.rsmi_topo_numa_affinity_get(cDv_ind, cNuma_node)
	runtime.KeepAlive(cNuma_nodeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_pci_throughput_get function as declared in rocm_smi/rocm_smi.h:1496
func rsmi_dev_pci_throughput_get(Dv_ind uint32, Sent *uint64, Received *uint64, Max_pkt_sz *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSent, cSentAllocMap := (*C.ulonglong)(unsafe.Pointer(Sent)), cgoAllocsUnknown
	cReceived, cReceivedAllocMap := (*C.ulonglong)(unsafe.Pointer(Received)), cgoAllocsUnknown
	cMax_pkt_sz, cMax_pkt_szAllocMap := (*C.ulonglong)(unsafe.Pointer(Max_pkt_sz)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_throughput_get(cDv_ind, cSent, cReceived, cMax_pkt_sz)
	runtime.KeepAlive(cMax_pkt_szAllocMap)
	runtime.KeepAlive(cReceivedAllocMap)
	runtime.KeepAlive(cSentAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_pci_replay_counter_get function as declared in rocm_smi/rocm_smi.h:1521
func rsmi_dev_pci_replay_counter_get(Dv_ind uint32, Counter *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cCounter, cCounterAllocMap := (*C.ulonglong)(unsafe.Pointer(Counter)), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_replay_counter_get(cDv_ind, cCounter)
	runtime.KeepAlive(cCounterAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_pci_bandwidth_set function as declared in rocm_smi/rocm_smi.h:1560
func rsmi_dev_pci_bandwidth_set(Dv_ind uint32, Bw_bitmask uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBw_bitmask, cBw_bitmaskAllocMap := (C.ulonglong)(Bw_bitmask), cgoAllocsUnknown
	__ret := C.rsmi_dev_pci_bandwidth_set(cDv_ind, cBw_bitmask)
	runtime.KeepAlive(cBw_bitmaskAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_ave_get function as declared in rocm_smi/rocm_smi.h:1595
func rsmi_dev_power_ave_get(Dv_ind uint32, Sensor_ind uint32, Power *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.ulonglong)(unsafe.Pointer(Power)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_ave_get(cDv_ind, cSensor_ind, cPower)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_energy_count_get function as declared in rocm_smi/rocm_smi.h:1628
func rsmi_dev_energy_count_get(Dv_ind uint32, Power *uint64, Counter_resolution *float32, Timestamp *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.ulonglong)(unsafe.Pointer(Power)), cgoAllocsUnknown
	cCounter_resolution, cCounter_resolutionAllocMap := (*C.float)(unsafe.Pointer(Counter_resolution)), cgoAllocsUnknown
	cTimestamp, cTimestampAllocMap := (*C.ulonglong)(unsafe.Pointer(Timestamp)), cgoAllocsUnknown
	__ret := C.rsmi_dev_energy_count_get(cDv_ind, cPower, cCounter_resolution, cTimestamp)
	runtime.KeepAlive(cTimestampAllocMap)
	runtime.KeepAlive(cCounter_resolutionAllocMap)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_get function as declared in rocm_smi/rocm_smi.h:1657
func rsmi_dev_power_cap_get(Dv_ind uint32, Sensor_ind uint32, Cap *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cCap, cCapAllocMap := (*C.ulonglong)(unsafe.Pointer(Cap)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_get(cDv_ind, cSensor_ind, cCap)
	runtime.KeepAlive(cCapAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_default_get function as declared in rocm_smi/rocm_smi.h:1681
func rsmi_dev_power_cap_default_get(Dv_ind uint32, Default_cap *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cDefault_cap, cDefault_capAllocMap := (*C.ulonglong)(unsafe.Pointer(Default_cap)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_default_get(cDv_ind, cDefault_cap)
	runtime.KeepAlive(cDefault_capAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_range_get function as declared in rocm_smi/rocm_smi.h:1715
func rsmi_dev_power_cap_range_get(Dv_ind uint32, Sensor_ind uint32, Max *uint64, Min *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cMax, cMaxAllocMap := (*C.ulonglong)(unsafe.Pointer(Max)), cgoAllocsUnknown
	cMin, cMinAllocMap := (*C.ulonglong)(unsafe.Pointer(Min)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_range_get(cDv_ind, cSensor_ind, cMax, cMin)
	runtime.KeepAlive(cMinAllocMap)
	runtime.KeepAlive(cMaxAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_cap_set function as declared in rocm_smi/rocm_smi.h:1746
func rsmi_dev_power_cap_set(Dv_ind uint32, Sensor_ind uint32, Cap uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cCap, cCapAllocMap := (C.ulonglong)(Cap), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_cap_set(cDv_ind, cSensor_ind, cCap)
	runtime.KeepAlive(cCapAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_profile_set function as declared in rocm_smi/rocm_smi.h:1768
func rsmi_dev_power_profile_set(Dv_ind uint32, Reserved uint32, Profile RSMI_power_profile_preset_masks) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cReserved, cReservedAllocMap := (C.uint32_t)(Reserved), cgoAllocsUnknown
	cProfile, cProfileAllocMap := (C.rsmi_power_profile_preset_masks_t)(Profile), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_profile_set(cDv_ind, cReserved, cProfile)
	runtime.KeepAlive(cProfileAllocMap)
	runtime.KeepAlive(cReservedAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_memory_total_get function as declared in rocm_smi/rocm_smi.h:1807
func rsmi_dev_memory_total_get(Dv_ind uint32, Mem_type RSMI_memory_type, Total *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cMem_type, cMem_typeAllocMap := (C.rsmi_memory_type_t)(Mem_type), cgoAllocsUnknown
	cTotal, cTotalAllocMap := (*C.ulonglong)(unsafe.Pointer(Total)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_total_get(cDv_ind, cMem_type, cTotal)
	runtime.KeepAlive(cTotalAllocMap)
	runtime.KeepAlive(cMem_typeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_memory_usage_get function as declared in rocm_smi/rocm_smi.h:1837
func rsmi_dev_memory_usage_get(Dv_ind uint32, Mem_type RSMI_memory_type, Used *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cMem_type, cMem_typeAllocMap := (C.rsmi_memory_type_t)(Mem_type), cgoAllocsUnknown
	cUsed, cUsedAllocMap := (*C.ulonglong)(unsafe.Pointer(Used)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_usage_get(cDv_ind, cMem_type, cUsed)
	runtime.KeepAlive(cUsedAllocMap)
	runtime.KeepAlive(cMem_typeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_memory_busy_percent_get function as declared in rocm_smi/rocm_smi.h:1863
func rsmi_dev_memory_busy_percent_get(Dv_ind uint32, Busy_percent *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBusy_percent, cBusy_percentAllocMap := (*C.uint32_t)(unsafe.Pointer(Busy_percent)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_busy_percent_get(cDv_ind, cBusy_percent)
	runtime.KeepAlive(cBusy_percentAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_memory_reserved_pages_get function as declared in rocm_smi/rocm_smi.h:1901
func rsmi_dev_memory_reserved_pages_get(Dv_ind uint32, Num_pages *uint32, Records *RSMI_retired_page_record) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cNum_pages, cNum_pagesAllocMap := (*C.uint32_t)(unsafe.Pointer(Num_pages)), cgoAllocsUnknown
	cRecords, cRecordsAllocMap := (*C.rsmi_retired_page_record_t)(unsafe.Pointer(Records)), cgoAllocsUnknown
	__ret := C.rsmi_dev_memory_reserved_pages_get(cDv_ind, cNum_pages, cRecords)
	runtime.KeepAlive(cRecordsAllocMap)
	runtime.KeepAlive(cNum_pagesAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_fan_rpms_get function as declared in rocm_smi/rocm_smi.h:1936
func rsmi_dev_fan_rpms_get(Dv_ind uint32, Sensor_ind uint32, Speed *int64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (*C.longlong)(unsafe.Pointer(Speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_rpms_get(cDv_ind, cSensor_ind, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_fan_speed_get function as declared in rocm_smi/rocm_smi.h:1966
func rsmi_dev_fan_speed_get(Dv_ind uint32, Sensor_ind uint32, Speed *int64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (*C.longlong)(unsafe.Pointer(Speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_get(cDv_ind, cSensor_ind, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_fan_speed_max_get function as declared in rocm_smi/rocm_smi.h:1994
func rsmi_dev_fan_speed_max_get(Dv_ind uint32, Sensor_ind uint32, Max_speed *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cMax_speed, cMax_speedAllocMap := (*C.ulonglong)(unsafe.Pointer(Max_speed)), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_max_get(cDv_ind, cSensor_ind, cMax_speed)
	runtime.KeepAlive(cMax_speedAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_temp_metric_get function as declared in rocm_smi/rocm_smi.h:2027
func rsmi_dev_temp_metric_get(Dv_ind uint32, Sensor_type uint32, Metric RSMI_temperature_metric, Temperature *int64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_type, cSensor_typeAllocMap := (C.uint32_t)(Sensor_type), cgoAllocsUnknown
	cMetric, cMetricAllocMap := (C.rsmi_temperature_metric_t)(Metric), cgoAllocsUnknown
	cTemperature, cTemperatureAllocMap := (*C.longlong)(unsafe.Pointer(Temperature)), cgoAllocsUnknown
	__ret := C.rsmi_dev_temp_metric_get(cDv_ind, cSensor_type, cMetric, cTemperature)
	runtime.KeepAlive(cTemperatureAllocMap)
	runtime.KeepAlive(cMetricAllocMap)
	runtime.KeepAlive(cSensor_typeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_volt_metric_get function as declared in rocm_smi/rocm_smi.h:2060
func rsmi_dev_volt_metric_get(Dv_ind uint32, Sensor_type RSMI_voltage_type, Metric RSMI_voltage_metric, Voltage *int64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_type, cSensor_typeAllocMap := (C.rsmi_voltage_type_t)(Sensor_type), cgoAllocsUnknown
	cMetric, cMetricAllocMap := (C.rsmi_voltage_metric_t)(Metric), cgoAllocsUnknown
	cVoltage, cVoltageAllocMap := (*C.longlong)(unsafe.Pointer(Voltage)), cgoAllocsUnknown
	__ret := C.rsmi_dev_volt_metric_get(cDv_ind, cSensor_type, cMetric, cVoltage)
	runtime.KeepAlive(cVoltageAllocMap)
	runtime.KeepAlive(cMetricAllocMap)
	runtime.KeepAlive(cSensor_typeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_fan_reset function as declared in rocm_smi/rocm_smi.h:2085
func rsmi_dev_fan_reset(Dv_ind uint32, Sensor_ind uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_reset(cDv_ind, cSensor_ind)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_fan_speed_set function as declared in rocm_smi/rocm_smi.h:2109
func rsmi_dev_fan_speed_set(Dv_ind uint32, Sensor_ind uint32, Speed uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cSpeed, cSpeedAllocMap := (C.ulonglong)(Speed), cgoAllocsUnknown
	__ret := C.rsmi_dev_fan_speed_set(cDv_ind, cSensor_ind, cSpeed)
	runtime.KeepAlive(cSpeedAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_busy_percent_get function as declared in rocm_smi/rocm_smi.h:2144
func rsmi_dev_busy_percent_get(Dv_ind uint32, Busy_percent *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBusy_percent, cBusy_percentAllocMap := (*C.uint32_t)(unsafe.Pointer(Busy_percent)), cgoAllocsUnknown
	__ret := C.rsmi_dev_busy_percent_get(cDv_ind, cBusy_percent)
	runtime.KeepAlive(cBusy_percentAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_utilization_count_get function as declared in rocm_smi/rocm_smi.h:2176
func rsmi_utilization_count_get(Dv_ind uint32, Utilization_counters *RSMI_utilization_counter, Count uint32, Timestamp *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cUtilization_counters, cUtilization_countersAllocMap := (*C.rsmi_utilization_counter_t)(unsafe.Pointer(Utilization_counters)), cgoAllocsUnknown
	cCount, cCountAllocMap := (C.uint32_t)(Count), cgoAllocsUnknown
	cTimestamp, cTimestampAllocMap := (*C.ulonglong)(unsafe.Pointer(Timestamp)), cgoAllocsUnknown
	__ret := C.rsmi_utilization_count_get(cDv_ind, cUtilization_counters, cCount, cTimestamp)
	runtime.KeepAlive(cTimestampAllocMap)
	runtime.KeepAlive(cCountAllocMap)
	runtime.KeepAlive(cUtilization_countersAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_perf_level_get function as declared in rocm_smi/rocm_smi.h:2204
func rsmi_dev_perf_level_get(Dv_ind uint32, Perf *RSMI_dev_perf_level) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cPerf, cPerfAllocMap := (*C.rsmi_dev_perf_level_t)(unsafe.Pointer(Perf)), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_get(cDv_ind, cPerf)
	runtime.KeepAlive(cPerfAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_perf_determinism_mode_set function as declared in rocm_smi/rocm_smi.h:2229
func rsmi_perf_determinism_mode_set(Dv_ind uint32, Clkvalue uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.ulonglong)(Clkvalue), cgoAllocsUnknown
	__ret := C.rsmi_perf_determinism_mode_set(cDv_ind, cClkvalue)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_overdrive_level_get function as declared in rocm_smi/rocm_smi.h:2254
func rsmi_dev_overdrive_level_get(Dv_ind uint32, Od *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cOd, cOdAllocMap := (*C.uint32_t)(unsafe.Pointer(Od)), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_get(cDv_ind, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_gpu_clk_freq_get function as declared in rocm_smi/rocm_smi.h:2283
func rsmi_dev_gpu_clk_freq_get(Dv_ind uint32, Clk_type RSMI_clk_type, F *RSMI_frequencies) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cClk_type, cClk_typeAllocMap := (C.rsmi_clk_type_t)(Clk_type), cgoAllocsUnknown
	cF, cFAllocMap := (*C.rsmi_frequencies_t)(unsafe.Pointer(F)), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_clk_freq_get(cDv_ind, cClk_type, cF)
	runtime.KeepAlive(cFAllocMap)
	runtime.KeepAlive(cClk_typeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_gpu_reset function as declared in rocm_smi/rocm_smi.h:2299
func rsmi_dev_gpu_reset(Dv_ind int32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.int32_t)(Dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_reset(cDv_ind)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_od_volt_info_get function as declared in rocm_smi/rocm_smi.h:2321
func rsmi_dev_od_volt_info_get(Dv_ind uint32, Odv *RSMI_od_volt_freq_data) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cOdv, cOdvAllocMap := (*C.rsmi_od_volt_freq_data_t)(unsafe.Pointer(Odv)), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_info_get(cDv_ind, cOdv)
	runtime.KeepAlive(cOdvAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_gpu_metrics_info_get function as declared in rocm_smi/rocm_smi.h:2344
func rsmi_dev_gpu_metrics_info_get(Dv_ind uint32, Pgpu_metrics *RSMI_gpu_metrics) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cPgpu_metrics, cPgpu_metricsAllocMap := (*C.rsmi_gpu_metrics_t)(unsafe.Pointer(Pgpu_metrics)), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_metrics_info_get(cDv_ind, cPgpu_metrics)
	runtime.KeepAlive(cPgpu_metricsAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_clk_range_set function as declared in rocm_smi/rocm_smi.h:2369
func rsmi_dev_clk_range_set(Dv_ind uint32, Minclkvalue uint64, Maxclkvalue uint64, ClkType RSMI_clk_type) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cMinclkvalue, cMinclkvalueAllocMap := (C.ulonglong)(Minclkvalue), cgoAllocsUnknown
	cMaxclkvalue, cMaxclkvalueAllocMap := (C.ulonglong)(Maxclkvalue), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_clk_range_set(cDv_ind, cMinclkvalue, cMaxclkvalue, cClkType)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cMaxclkvalueAllocMap)
	runtime.KeepAlive(cMinclkvalueAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_od_clk_info_set function as declared in rocm_smi/rocm_smi.h:2395
func rsmi_dev_od_clk_info_set(Dv_ind uint32, Level RSMI_freq_ind, Clkvalue uint64, ClkType RSMI_clk_type) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cLevel, cLevelAllocMap := (C.rsmi_freq_ind_t)(Level), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.ulonglong)(Clkvalue), cgoAllocsUnknown
	cClkType, cClkTypeAllocMap := (C.rsmi_clk_type_t)(ClkType), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_clk_info_set(cDv_ind, cLevel, cClkvalue, cClkType)
	runtime.KeepAlive(cClkTypeAllocMap)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cLevelAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_od_volt_info_set function as declared in rocm_smi/rocm_smi.h:2420
func rsmi_dev_od_volt_info_set(Dv_ind uint32, Vpoint uint32, Clkvalue uint64, Voltvalue uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cVpoint, cVpointAllocMap := (C.uint32_t)(Vpoint), cgoAllocsUnknown
	cClkvalue, cClkvalueAllocMap := (C.ulonglong)(Clkvalue), cgoAllocsUnknown
	cVoltvalue, cVoltvalueAllocMap := (C.ulonglong)(Voltvalue), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_info_set(cDv_ind, cVpoint, cClkvalue, cVoltvalue)
	runtime.KeepAlive(cVoltvalueAllocMap)
	runtime.KeepAlive(cClkvalueAllocMap)
	runtime.KeepAlive(cVpointAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_od_volt_curve_regions_get function as declared in rocm_smi/rocm_smi.h:2461
func rsmi_dev_od_volt_curve_regions_get(Dv_ind uint32, Num_regions *uint32, Buffer *RSMI_freq_volt_region) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cNum_regions, cNum_regionsAllocMap := (*C.uint32_t)(unsafe.Pointer(Num_regions)), cgoAllocsUnknown
	cBuffer, cBufferAllocMap := (*C.rsmi_freq_volt_region_t)(unsafe.Pointer(Buffer)), cgoAllocsUnknown
	__ret := C.rsmi_dev_od_volt_curve_regions_get(cDv_ind, cNum_regions, cBuffer)
	runtime.KeepAlive(cBufferAllocMap)
	runtime.KeepAlive(cNum_regionsAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_power_profile_presets_get function as declared in rocm_smi/rocm_smi.h:2500
func rsmi_dev_power_profile_presets_get(Dv_ind uint32, Sensor_ind uint32, Status *RSMI_power_profile_status) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cSensor_ind, cSensor_indAllocMap := (C.uint32_t)(Sensor_ind), cgoAllocsUnknown
	cStatus, cStatusAllocMap := (*C.rsmi_power_profile_status_t)(unsafe.Pointer(Status)), cgoAllocsUnknown
	__ret := C.rsmi_dev_power_profile_presets_get(cDv_ind, cSensor_ind, cStatus)
	runtime.KeepAlive(cStatusAllocMap)
	runtime.KeepAlive(cSensor_indAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_perf_level_set function as declared in rocm_smi/rocm_smi.h:2533
func rsmi_dev_perf_level_set(Dv_ind int32, Perf_lvl RSMI_dev_perf_level) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.int32_t)(Dv_ind), cgoAllocsUnknown
	cPerf_lvl, cPerf_lvlAllocMap := (C.rsmi_dev_perf_level_t)(Perf_lvl), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_set(cDv_ind, cPerf_lvl)
	runtime.KeepAlive(cPerf_lvlAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_perf_level_set_v1 function as declared in rocm_smi/rocm_smi.h:2554
func rsmi_dev_perf_level_set_v1(Dv_ind uint32, Perf_lvl RSMI_dev_perf_level) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cPerf_lvl, cPerf_lvlAllocMap := (C.rsmi_dev_perf_level_t)(Perf_lvl), cgoAllocsUnknown
	__ret := C.rsmi_dev_perf_level_set_v1(cDv_ind, cPerf_lvl)
	runtime.KeepAlive(cPerf_lvlAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_overdrive_level_set function as declared in rocm_smi/rocm_smi.h:2599
func rsmi_dev_overdrive_level_set(Dv_ind int32, Od uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.int32_t)(Dv_ind), cgoAllocsUnknown
	cOd, cOdAllocMap := (C.uint32_t)(Od), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_set(cDv_ind, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_overdrive_level_set_v1 function as declared in rocm_smi/rocm_smi.h:2640
func rsmi_dev_overdrive_level_set_v1(Dv_ind uint32, Od uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cOd, cOdAllocMap := (C.uint32_t)(Od), cgoAllocsUnknown
	__ret := C.rsmi_dev_overdrive_level_set_v1(cDv_ind, cOd)
	runtime.KeepAlive(cOdAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_gpu_clk_freq_set function as declared in rocm_smi/rocm_smi.h:2676
func rsmi_dev_gpu_clk_freq_set(Dv_ind uint32, Clk_type RSMI_clk_type, Freq_bitmask uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cClk_type, cClk_typeAllocMap := (C.rsmi_clk_type_t)(Clk_type), cgoAllocsUnknown
	cFreq_bitmask, cFreq_bitmaskAllocMap := (C.ulonglong)(Freq_bitmask), cgoAllocsUnknown
	__ret := C.rsmi_dev_gpu_clk_freq_set(cDv_ind, cClk_type, cFreq_bitmask)
	runtime.KeepAlive(cFreq_bitmaskAllocMap)
	runtime.KeepAlive(cClk_typeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_version_get function as declared in rocm_smi/rocm_smi.h:2701
func rsmi_version_get(Version *RSMI_version) RSMI_status {
	cVersion, cVersionAllocMap := (*C.rsmi_version_t)(unsafe.Pointer(Version)), cgoAllocsUnknown
	__ret := C.rsmi_version_get(cVersion)
	runtime.KeepAlive(cVersionAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_version_str_get function as declared in rocm_smi/rocm_smi.h:2729
func rsmi_version_str_get(Component RSMI_sw_component, Ver_str *byte, Len uint32) RSMI_status {
	cComponent, cComponentAllocMap := (C.rsmi_sw_component_t)(Component), cgoAllocsUnknown
	cVer_str, cVer_strAllocMap := (*C.char)(unsafe.Pointer(Ver_str)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_version_str_get(cComponent, cVer_str, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cVer_strAllocMap)
	runtime.KeepAlive(cComponentAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_vbios_version_get function as declared in rocm_smi/rocm_smi.h:2759
func rsmi_dev_vbios_version_get(Dv_ind uint32, Vbios *byte, Len uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cVbios, cVbiosAllocMap := (*C.char)(unsafe.Pointer(Vbios)), cgoAllocsUnknown
	cLen, cLenAllocMap := (C.uint32_t)(Len), cgoAllocsUnknown
	__ret := C.rsmi_dev_vbios_version_get(cDv_ind, cVbios, cLen)
	runtime.KeepAlive(cLenAllocMap)
	runtime.KeepAlive(cVbiosAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_firmware_version_get function as declared in rocm_smi/rocm_smi.h:2786
func rsmi_dev_firmware_version_get(Dv_ind uint32, Block RSMI_fw_block, Fw_version *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBlock, cBlockAllocMap := (C.rsmi_fw_block_t)(Block), cgoAllocsUnknown
	cFw_version, cFw_versionAllocMap := (*C.ulonglong)(unsafe.Pointer(Fw_version)), cgoAllocsUnknown
	__ret := C.rsmi_dev_firmware_version_get(cDv_ind, cBlock, cFw_version)
	runtime.KeepAlive(cFw_versionAllocMap)
	runtime.KeepAlive(cBlockAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_ecc_count_get function as declared in rocm_smi/rocm_smi.h:2823
func rsmi_dev_ecc_count_get(Dv_ind uint32, Block RSMI_gpu_block, Ec *RSMI_error_count) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBlock, cBlockAllocMap := (C.rsmi_gpu_block_t)(Block), cgoAllocsUnknown
	cEc, cEcAllocMap := (*C.rsmi_error_count_t)(unsafe.Pointer(Ec)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_count_get(cDv_ind, cBlock, cEc)
	runtime.KeepAlive(cEcAllocMap)
	runtime.KeepAlive(cBlockAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_ecc_enabled_get function as declared in rocm_smi/rocm_smi.h:2853
func rsmi_dev_ecc_enabled_get(Dv_ind uint32, Enabled_blocks *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cEnabled_blocks, cEnabled_blocksAllocMap := (*C.ulonglong)(unsafe.Pointer(Enabled_blocks)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_enabled_get(cDv_ind, cEnabled_blocks)
	runtime.KeepAlive(cEnabled_blocksAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_ecc_status_get function as declared in rocm_smi/rocm_smi.h:2881
func rsmi_dev_ecc_status_get(Dv_ind uint32, Block RSMI_gpu_block, State *RSMI_ras_err_state) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cBlock, cBlockAllocMap := (C.rsmi_gpu_block_t)(Block), cgoAllocsUnknown
	cState, cStateAllocMap := (*C.rsmi_ras_err_state_t)(unsafe.Pointer(State)), cgoAllocsUnknown
	__ret := C.rsmi_dev_ecc_status_get(cDv_ind, cBlock, cState)
	runtime.KeepAlive(cStateAllocMap)
	runtime.KeepAlive(cBlockAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_counter_group_supported function as declared in rocm_smi/rocm_smi.h:3024
func rsmi_dev_counter_group_supported(Dv_ind uint32, Group RSMI_event_group) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cGroup, cGroupAllocMap := (C.rsmi_event_group_t)(Group), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_group_supported(cDv_ind, cGroup)
	runtime.KeepAlive(cGroupAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_counter_create function as declared in rocm_smi/rocm_smi.h:3055
func rsmi_dev_counter_create(Dv_ind uint32, Type RSMI_event_type, Evnt_handle *RSMI_event_handle) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cType, cTypeAllocMap := (C.rsmi_event_type_t)(Type), cgoAllocsUnknown
	cEvnt_handle, cEvnt_handleAllocMap := (*C.rsmi_event_handle_t)(unsafe.Pointer(Evnt_handle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_create(cDv_ind, cType, cEvnt_handle)
	runtime.KeepAlive(cEvnt_handleAllocMap)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_counter_destroy function as declared in rocm_smi/rocm_smi.h:3072
func rsmi_dev_counter_destroy(Evnt_handle RSMI_event_handle) RSMI_status {
	cEvnt_handle, cEvnt_handleAllocMap := (C.rsmi_event_handle_t)(Evnt_handle), cgoAllocsUnknown
	__ret := C.rsmi_dev_counter_destroy(cEvnt_handle)
	runtime.KeepAlive(cEvnt_handleAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_counter_control function as declared in rocm_smi/rocm_smi.h:3092
func rsmi_counter_control(Evt_handle RSMI_event_handle, Cmd RSMI_counter_command, Cmd_args unsafe.Pointer) RSMI_status {
	cEvt_handle, cEvt_handleAllocMap := (C.rsmi_event_handle_t)(Evt_handle), cgoAllocsUnknown
	cCmd, cCmdAllocMap := (C.rsmi_counter_command_t)(Cmd), cgoAllocsUnknown
	cCmd_args, cCmd_argsAllocMap := Cmd_args, cgoAllocsUnknown
	__ret := C.rsmi_counter_control(cEvt_handle, cCmd, cCmd_args)
	runtime.KeepAlive(cCmd_argsAllocMap)
	runtime.KeepAlive(cCmdAllocMap)
	runtime.KeepAlive(cEvt_handleAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_counter_read function as declared in rocm_smi/rocm_smi.h:3113
func rsmi_counter_read(Evt_handle RSMI_event_handle, Value *RSMI_counter_value) RSMI_status {
	cEvt_handle, cEvt_handleAllocMap := (C.rsmi_event_handle_t)(Evt_handle), cgoAllocsUnknown
	cValue, cValueAllocMap := (*C.rsmi_counter_value_t)(unsafe.Pointer(Value)), cgoAllocsUnknown
	__ret := C.rsmi_counter_read(cEvt_handle, cValue)
	runtime.KeepAlive(cValueAllocMap)
	runtime.KeepAlive(cEvt_handleAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_counter_available_counters_get function as declared in rocm_smi/rocm_smi.h:3136
func rsmi_counter_available_counters_get(Dv_ind uint32, Grp RSMI_event_group, Available *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cGrp, cGrpAllocMap := (C.rsmi_event_group_t)(Grp), cgoAllocsUnknown
	cAvailable, cAvailableAllocMap := (*C.uint32_t)(unsafe.Pointer(Available)), cgoAllocsUnknown
	__ret := C.rsmi_counter_available_counters_get(cDv_ind, cGrp, cAvailable)
	runtime.KeepAlive(cAvailableAllocMap)
	runtime.KeepAlive(cGrpAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_compute_process_info_get function as declared in rocm_smi/rocm_smi.h:3179
func rsmi_compute_process_info_get(Procs *RSMI_process_info, Num_items *uint32) RSMI_status {
	cProcs, cProcsAllocMap := (*C.rsmi_process_info_t)(unsafe.Pointer(Procs)), cgoAllocsUnknown
	cNum_items, cNum_itemsAllocMap := (*C.uint32_t)(unsafe.Pointer(Num_items)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_info_get(cProcs, cNum_items)
	runtime.KeepAlive(cNum_itemsAllocMap)
	runtime.KeepAlive(cProcsAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_compute_process_info_by_pid_get function as declared in rocm_smi/rocm_smi.h:3203
func rsmi_compute_process_info_by_pid_get(Pid uint32, Proc *RSMI_process_info) RSMI_status {
	cPid, cPidAllocMap := (C.uint32_t)(Pid), cgoAllocsUnknown
	cProc, cProcAllocMap := (*C.rsmi_process_info_t)(unsafe.Pointer(Proc)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_info_by_pid_get(cPid, cProc)
	runtime.KeepAlive(cProcAllocMap)
	runtime.KeepAlive(cPidAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_compute_process_gpus_get function as declared in rocm_smi/rocm_smi.h:3240
func rsmi_compute_process_gpus_get(Pid uint32, Dv_indices *uint32, Num_devices *uint32) RSMI_status {
	cPid, cPidAllocMap := (C.uint32_t)(Pid), cgoAllocsUnknown
	cDv_indices, cDv_indicesAllocMap := (*C.uint32_t)(unsafe.Pointer(Dv_indices)), cgoAllocsUnknown
	cNum_devices, cNum_devicesAllocMap := (*C.uint32_t)(unsafe.Pointer(Num_devices)), cgoAllocsUnknown
	__ret := C.rsmi_compute_process_gpus_get(cPid, cDv_indices, cNum_devices)
	runtime.KeepAlive(cNum_devicesAllocMap)
	runtime.KeepAlive(cDv_indicesAllocMap)
	runtime.KeepAlive(cPidAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_error_status function as declared in rocm_smi/rocm_smi.h:3275
func rsmi_dev_xgmi_error_status(Dv_ind uint32, Status *RSMI_xgmi_status) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cStatus, cStatusAllocMap := (*C.rsmi_xgmi_status_t)(unsafe.Pointer(Status)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_error_status(cDv_ind, cStatus)
	runtime.KeepAlive(cStatusAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_error_reset function as declared in rocm_smi/rocm_smi.h:3290
func rsmi_dev_xgmi_error_reset(Dv_ind uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_error_reset(cDv_ind)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_xgmi_hive_id_get function as declared in rocm_smi/rocm_smi.h:3311
func rsmi_dev_xgmi_hive_id_get(Dv_ind uint32, Hive_id *uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cHive_id, cHive_idAllocMap := (*C.ulonglong)(unsafe.Pointer(Hive_id)), cgoAllocsUnknown
	__ret := C.rsmi_dev_xgmi_hive_id_get(cDv_ind, cHive_id)
	runtime.KeepAlive(cHive_idAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_topo_get_numa_node_number function as declared in rocm_smi/rocm_smi.h:3339
func rsmi_topo_get_numa_node_number(Dv_ind uint32, Numa_node *uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cNuma_node, cNuma_nodeAllocMap := (*C.uint32_t)(unsafe.Pointer(Numa_node)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_numa_node_number(cDv_ind, cNuma_node)
	runtime.KeepAlive(cNuma_nodeAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_topo_get_link_weight function as declared in rocm_smi/rocm_smi.h:3362
func rsmi_topo_get_link_weight(Dv_ind_src uint32, Dv_ind_dst uint32, Weight *uint64) RSMI_status {
	cDv_ind_src, cDv_ind_srcAllocMap := (C.uint32_t)(Dv_ind_src), cgoAllocsUnknown
	cDv_ind_dst, cDv_ind_dstAllocMap := (C.uint32_t)(Dv_ind_dst), cgoAllocsUnknown
	cWeight, cWeightAllocMap := (*C.ulonglong)(unsafe.Pointer(Weight)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_link_weight(cDv_ind_src, cDv_ind_dst, cWeight)
	runtime.KeepAlive(cWeightAllocMap)
	runtime.KeepAlive(cDv_ind_dstAllocMap)
	runtime.KeepAlive(cDv_ind_srcAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_minmax_bandwidth_get function as declared in rocm_smi/rocm_smi.h:3388
func rsmi_minmax_bandwidth_get(Dv_ind_src uint32, Dv_ind_dst uint32, Min_bandwidth *uint64, Max_bandwidth *uint64) RSMI_status {
	cDv_ind_src, cDv_ind_srcAllocMap := (C.uint32_t)(Dv_ind_src), cgoAllocsUnknown
	cDv_ind_dst, cDv_ind_dstAllocMap := (C.uint32_t)(Dv_ind_dst), cgoAllocsUnknown
	cMin_bandwidth, cMin_bandwidthAllocMap := (*C.ulonglong)(unsafe.Pointer(Min_bandwidth)), cgoAllocsUnknown
	cMax_bandwidth, cMax_bandwidthAllocMap := (*C.ulonglong)(unsafe.Pointer(Max_bandwidth)), cgoAllocsUnknown
	__ret := C.rsmi_minmax_bandwidth_get(cDv_ind_src, cDv_ind_dst, cMin_bandwidth, cMax_bandwidth)
	runtime.KeepAlive(cMax_bandwidthAllocMap)
	runtime.KeepAlive(cMin_bandwidthAllocMap)
	runtime.KeepAlive(cDv_ind_dstAllocMap)
	runtime.KeepAlive(cDv_ind_srcAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_topo_get_link_type function as declared in rocm_smi/rocm_smi.h:3416
func rsmi_topo_get_link_type(Dv_ind_src uint32, Dv_ind_dst uint32, Hops *uint64, Type *RSMI_IO_LINK_TYPE) RSMI_status {
	cDv_ind_src, cDv_ind_srcAllocMap := (C.uint32_t)(Dv_ind_src), cgoAllocsUnknown
	cDv_ind_dst, cDv_ind_dstAllocMap := (C.uint32_t)(Dv_ind_dst), cgoAllocsUnknown
	cHops, cHopsAllocMap := (*C.ulonglong)(unsafe.Pointer(Hops)), cgoAllocsUnknown
	cType, cTypeAllocMap := (*C.RSMI_IO_LINK_TYPE)(unsafe.Pointer(Type)), cgoAllocsUnknown
	__ret := C.rsmi_topo_get_link_type(cDv_ind_src, cDv_ind_dst, cHops, cType)
	runtime.KeepAlive(cTypeAllocMap)
	runtime.KeepAlive(cHopsAllocMap)
	runtime.KeepAlive(cDv_ind_dstAllocMap)
	runtime.KeepAlive(cDv_ind_srcAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_is_P2P_accessible function as declared in rocm_smi/rocm_smi.h:3440
func rsmi_is_P2P_accessible(Dv_ind_src uint32, Dv_ind_dst uint32, Accessible *bool) RSMI_status {
	cDv_ind_src, cDv_ind_srcAllocMap := (C.uint32_t)(Dv_ind_src), cgoAllocsUnknown
	cDv_ind_dst, cDv_ind_dstAllocMap := (C.uint32_t)(Dv_ind_dst), cgoAllocsUnknown
	cAccessible, cAccessibleAllocMap := (*C._Bool)(unsafe.Pointer(Accessible)), cgoAllocsUnknown
	__ret := C.rsmi_is_P2P_accessible(cDv_ind_src, cDv_ind_dst, cAccessible)
	runtime.KeepAlive(cAccessibleAllocMap)
	runtime.KeepAlive(cDv_ind_dstAllocMap)
	runtime.KeepAlive(cDv_ind_srcAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_supported_func_iterator_open function as declared in rocm_smi/rocm_smi.h:3579
func rsmi_dev_supported_func_iterator_open(Dv_ind uint32, Handle *RSMI_func_id_iter_handle) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cHandle, cHandleAllocMap := (*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(Handle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_func_iterator_open(cDv_ind, cHandle)
	runtime.KeepAlive(cHandleAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_supported_variant_iterator_open function as declared in rocm_smi/rocm_smi.h:3607
func rsmi_dev_supported_variant_iterator_open(Obj_h RSMI_func_id_iter_handle, Var_iter *RSMI_func_id_iter_handle) RSMI_status {
	cObj_h, cObj_hAllocMap := *(*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(&Obj_h)), cgoAllocsUnknown
	cVar_iter, cVar_iterAllocMap := (*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(Var_iter)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_variant_iterator_open(cObj_h, cVar_iter)
	runtime.KeepAlive(cVar_iterAllocMap)
	runtime.KeepAlive(cObj_hAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_func_iter_next function as declared in rocm_smi/rocm_smi.h:3629
func rsmi_func_iter_next(Handle RSMI_func_id_iter_handle) RSMI_status {
	cHandle, cHandleAllocMap := *(*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(&Handle)), cgoAllocsUnknown
	__ret := C.rsmi_func_iter_next(cHandle)
	runtime.KeepAlive(cHandleAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_dev_supported_func_iterator_close function as declared in rocm_smi/rocm_smi.h:3643
func rsmi_dev_supported_func_iterator_close(Handle *RSMI_func_id_iter_handle) RSMI_status {
	cHandle, cHandleAllocMap := (*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(Handle)), cgoAllocsUnknown
	__ret := C.rsmi_dev_supported_func_iterator_close(cHandle)
	runtime.KeepAlive(cHandleAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_func_iter_value_get function as declared in rocm_smi/rocm_smi.h:3664
func rsmi_func_iter_value_get(Handle RSMI_func_id_iter_handle, Value *RSMI_func_id_value) RSMI_status {
	cHandle, cHandleAllocMap := *(*C.rsmi_func_id_iter_handle_t)(unsafe.Pointer(&Handle)), cgoAllocsUnknown
	cValue, cValueAllocMap := (*C.rsmi_func_id_value_t)(unsafe.Pointer(Value)), cgoAllocsUnknown
	__ret := C.rsmi_func_iter_value_get(cHandle, cValue)
	runtime.KeepAlive(cValueAllocMap)
	runtime.KeepAlive(cHandleAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_event_notification_init function as declared in rocm_smi/rocm_smi.h:3690
func rsmi_event_notification_init(Dv_ind uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_init(cDv_ind)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_event_notification_mask_set function as declared in rocm_smi/rocm_smi.h:3719
func rsmi_event_notification_mask_set(Dv_ind uint32, Mask uint64) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	cMask, cMaskAllocMap := (C.ulonglong)(Mask), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_mask_set(cDv_ind, cMask)
	runtime.KeepAlive(cMaskAllocMap)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_event_notification_get function as declared in rocm_smi/rocm_smi.h:3762
func rsmi_event_notification_get(Timeout_ms int32, Num_elem *uint32, Data *RSMI_evt_notification_data) RSMI_status {
	cTimeout_ms, cTimeout_msAllocMap := (C.int)(Timeout_ms), cgoAllocsUnknown
	cNum_elem, cNum_elemAllocMap := (*C.uint32_t)(unsafe.Pointer(Num_elem)), cgoAllocsUnknown
	cData, cDataAllocMap := (*C.rsmi_evt_notification_data_t)(unsafe.Pointer(Data)), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_get(cTimeout_ms, cNum_elem, cData)
	runtime.KeepAlive(cDataAllocMap)
	runtime.KeepAlive(cNum_elemAllocMap)
	runtime.KeepAlive(cTimeout_msAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_event_notification_stop function as declared in rocm_smi/rocm_smi.h:3783
func rsmi_event_notification_stop(Dv_ind uint32) RSMI_status {
	cDv_ind, cDv_indAllocMap := (C.uint32_t)(Dv_ind), cgoAllocsUnknown
	__ret := C.rsmi_event_notification_stop(cDv_ind)
	runtime.KeepAlive(cDv_indAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}

// rsmi_helper_func_variants_get function as declared in rocm_smi/rocm_smi_helpers.h:31
func rsmi_helper_func_variants_get(DeviceIndex uint32, Functions *RSMI_helper_function) RSMI_status {
	cDeviceIndex, cDeviceIndexAllocMap := (C.uint32_t)(DeviceIndex), cgoAllocsUnknown
	cFunctions, cFunctionsAllocMap := (*C.rsmi_helper_function_t)(unsafe.Pointer(Functions)), cgoAllocsUnknown
	__ret := C.rsmi_helper_func_variants_get(cDeviceIndex, cFunctions)
	runtime.KeepAlive(cFunctionsAllocMap)
	runtime.KeepAlive(cDeviceIndexAllocMap)
	__v := (RSMI_status)(__ret)
	return __v
}
