// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package rocm_smi

import "unsafe"

type RSMI_event_handle uint64

type RSMI_counter_value struct {
	Value	uint64
	Enabled	uint64
	Running	uint64
}

type RSMI_evt_notification_data struct {
	Ind	uint32
	Event	uint32
	Message	[96]int8
}

type RSMI_bit_field uint64

type RSMI_utilization_counter struct {
	Type	uint32
	Value	uint64
}

type RSMI_retired_page_record struct {
	Address		uint64
	Size		uint64
	Status		uint32
	Pad_cgo_0	[4]byte
}

type RSMI_power_profile_status struct {
	Available_profiles	uint64
	Current			int64
	Num_profiles		uint32
	Pad_cgo_0		[4]byte
}

type RSMI_frequencies struct {
	Has_deep_sleep	bool
	Num_supported	uint32
	Current		uint32
	Frequency	[33]uint64
}

type RSMI_pcie_bandwidth struct {
	Rate		RSMI_frequencies
	Lanes		[33]uint32
	Pad_cgo_0	[4]byte
}

type RSMI_activity_metric_counter struct {
	Gfx_activity	uint16
	Umc_activity	uint16
	Mm_activity	uint16
}

type RSMI_version struct {
	Major	uint32
	Minor	uint32
	Patch	uint32
	Build	*int8
}

type RSMI_range struct {
	Lower_bound	uint64
	Upper_bound	uint64
}

type RSMI_od_vddc_point struct {
	Frequency	uint64
	Voltage		uint64
}

type RSMI_freq_volt_region struct {
	Freq_range	RSMI_range
	Volt_range	RSMI_range
}

type RSMI_od_volt_curve struct {
	Points [3]RSMI_od_vddc_point
}

type RSMI_od_volt_freq_data struct {
	Curr_sclk_range		RSMI_range
	Curr_mclk_range		RSMI_range
	Sclk_freq_limits	RSMI_range
	Mclk_freq_limits	RSMI_range
	Curve			RSMI_od_volt_curve
	Num_regions		uint32
	Pad_cgo_0		[4]byte
}

type RSMI_gpu_metrics struct {
	Common_header			_Ctype_struct_metrics_table_header_t
	Temperature_edge		uint16
	Temperature_hotspot		uint16
	Temperature_mem			uint16
	Temperature_vrgfx		uint16
	Temperature_vrsoc		uint16
	Temperature_vrmem		uint16
	Average_gfx_activity		uint16
	Average_umc_activity		uint16
	Average_mm_activity		uint16
	Average_socket_power		uint16
	Energy_accumulator		uint64
	System_clock_counter		uint64
	Average_gfxclk_frequency	uint16
	Average_socclk_frequency	uint16
	Average_uclk_frequency		uint16
	Average_vclk0_frequency		uint16
	Average_dclk0_frequency		uint16
	Average_vclk1_frequency		uint16
	Average_dclk1_frequency		uint16
	Current_gfxclk			uint16
	Current_socclk			uint16
	Current_uclk			uint16
	Current_vclk0			uint16
	Current_dclk0			uint16
	Current_vclk1			uint16
	Current_dclk1			uint16
	Throttle_status			uint32
	Current_fan_speed		uint16
	Pcie_link_width			uint16
	Pcie_link_speed			uint16
	Gfx_activity_acc		uint32
	Mem_activity_acc		uint32
	Temperature_hbm			[4]uint16
	Firmware_timestamp		uint64
	Voltage_soc			uint16
	Voltage_gfx			uint16
	Voltage_mem			uint16
	Indep_throttle_status		uint64
	Current_socket_power		uint16
	Vcn_activity			[4]uint16
	Gfxclk_lock_status		uint32
	Xgmi_link_width			uint16
	Xgmi_link_speed			uint16
	Pcie_bandwidth_acc		uint64
	Pcie_bandwidth_inst		uint64
	Pcie_l0_to_recov_count_acc	uint64
	Pcie_replay_count_acc		uint64
	Pcie_replay_rover_count_acc	uint64
	Xgmi_read_data_acc		[8]uint64
	Xgmi_write_data_acc		[8]uint64
	Current_gfxclks			[8]uint16
	Current_socclks			[4]uint16
	Current_vclk0s			[4]uint16
	Current_dclk0s			[4]uint16
	Jpeg_activity			[32]uint16
	Pcie_nak_sent_count_acc		uint32
	Pcie_nak_rcvd_count_acc		uint32
	Accumulation_counter		uint64
	Prochot_residency_acc		uint64
	Ppt_residency_acc		uint64
	Socket_thm_residency_acc	uint64
	Vr_thm_residency_acc		uint64
	Hbm_thm_residency_acc		uint64
	Num_partition			uint16
	Xcp_stats			[8]_Ctype_struct_amdgpu_xcp_metrics_t
	Pcie_lc_perf_other_end_recovery	uint32
	Vram_max_bandwidth		uint64
	Xgmi_link_status		[8]uint16
}

type RSMI_error_count struct {
	Correctable_err		uint64
	Uncorrectable_err	uint64
}

type RSMI_process_info struct {
	Process_id	uint32
	Pasid		uint32
	Vram_usage	uint64
	Sdma_usage	uint64
	Cu_occupancy	uint32
	Pad_cgo_0	[4]byte
}

type RSMI_func_id_iter_handle *_Ctype_struct_rsmi_func_id_iter_handle

const sizeofRSMI_func_id_value = unsafe.Sizeof([8]byte{})

type RSMI_func_id_value [sizeofRSMI_func_id_value]byte

type RSMI_device_identifiers struct {
	Card_index		uint32
	Drm_render_minor	uint32
	Bdfid			uint64
	Kfd_gpu_id		uint64
	Partition_id		uint32
	Smi_device_id		uint32
	Reserved		[10]uint32
}

type RSMI_helper_variants struct {
	Num_variants	int32
	Variant_id	uint64
	Variantlist	[100]uint64
}

type RSMI_helper_function_variants struct {
	Name		[200]int8
	Sensors		int32
	Sensorlist	[30]RSMI_helper_variants
}

type RSMI_helper_function struct {
	Functions	int32
	Functionlist	[300]RSMI_helper_function_variants
}
