name: Go rocm-smi Build Tests

on:  
  push:
    tags:
      - '*'
    branches:
      - 'main'
      - 'ci-fix-attempts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # libdrm is required by kfd_ioctl.h
    - name: Install software
      run: sudo apt install golang libdrm-dev

    # The reason we use that specific commit hash is the following:
    # Today (2026-03-31) the latest stable release v1.3.0 handles
    # 'typedef struct foo * foo;' wrongly. So use the bleeding edge
    # version, which has a fix that we need.
    - name: Install c-for-go
      run: |
         go mod download github.com/NVIDIA/go-nvml
         go get github.com/xlab/c-for-go@6dd1c017f91eea5364499f7926d94583eaddaadb
         go install github.com/xlab/c-for-go@6dd1c017f91eea5364499f7926d94583eaddaadb
         sudo cp $(go env GOPATH)/bin/c-for-go /usr/local/bin
   
    - name: Get depdencies
      run: go get

    - name: Generate
      run: make

    - name: Build
      run: make build
  
#  publish:
#    runs-on: ubuntu-latest
#    needs:
#    - build-1-18
#    - build-1-17
#    - build-1-16
#    steps:
#    - uses: actions/checkout@v3
#
#    - name: Set up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.1
#
#    - name: Publish
#      run: |
#        export TAG=$(git describe --tags)
#        go list -m github.com/ClusterCockpit/go-rocm-smi/pkg/rocm_smi@${TAG}
